# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BurningToolDlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartBurningButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartBurningButton.setGeometry(QtCore.QRect(20, 20, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.StartBurningButton.setFont(font)
        self.StartBurningButton.setObjectName("StartBurningButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(780, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEditCheckSum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCheckSum.setGeometry(QtCore.QRect(880, 50, 113, 20))
        self.lineEditCheckSum.setObjectName("lineEditCheckSum")
        self.DetectPortButton = QtWidgets.QPushButton(self.centralwidget)
        self.DetectPortButton.setGeometry(QtCore.QRect(800, 120, 91, 31))
        self.DetectPortButton.setObjectName("DetectPortButton")
        self.OpenPortButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenPortButton.setGeometry(QtCore.QRect(890, 120, 91, 31))
        self.OpenPortButton.setObjectName("OpenPortButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 90, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 50, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 70, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(625, 30, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 70, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 50, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(320, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(320, 90, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(480, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(470, 50, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(470, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(625, 50, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(625, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(625, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEditMac1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac1.setGeometry(QtCore.QRect(190, 30, 113, 20))
        self.lineEditMac1.setObjectName("lineEditMac1")
        self.lineEditMac2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac2.setGeometry(QtCore.QRect(190, 50, 113, 20))
        self.lineEditMac2.setObjectName("lineEditMac2")
        self.lineEditMac3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac3.setGeometry(QtCore.QRect(190, 70, 113, 20))
        self.lineEditMac3.setObjectName("lineEditMac3")
        self.lineEditMac4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac4.setGeometry(QtCore.QRect(190, 90, 113, 20))
        self.lineEditMac4.setObjectName("lineEditMac4")
        self.lineEditMac5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac5.setGeometry(QtCore.QRect(340, 30, 113, 20))
        self.lineEditMac5.setObjectName("lineEditMac5")
        self.lineEditMac6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac6.setGeometry(QtCore.QRect(340, 50, 113, 20))
        self.lineEditMac6.setObjectName("lineEditMac6")
        self.lineEditMac7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac7.setGeometry(QtCore.QRect(340, 70, 113, 20))
        self.lineEditMac7.setObjectName("lineEditMac7")
        self.lineEditMac8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac8.setGeometry(QtCore.QRect(340, 90, 113, 20))
        self.lineEditMac8.setObjectName("lineEditMac8")
        self.lineEditMac9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac9.setGeometry(QtCore.QRect(500, 30, 113, 20))
        self.lineEditMac9.setObjectName("lineEditMac9")
        self.lineEditMac10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac10.setGeometry(QtCore.QRect(500, 50, 113, 20))
        self.lineEditMac10.setObjectName("lineEditMac10")
        self.lineEditMac11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac11.setGeometry(QtCore.QRect(500, 70, 113, 20))
        self.lineEditMac11.setObjectName("lineEditMac11")
        self.lineEditMac12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac12.setGeometry(QtCore.QRect(500, 90, 113, 20))
        self.lineEditMac12.setObjectName("lineEditMac12")
        self.lineEditMac13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac13.setGeometry(QtCore.QRect(650, 30, 113, 20))
        self.lineEditMac13.setObjectName("lineEditMac13")
        self.lineEditMac14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac14.setGeometry(QtCore.QRect(650, 50, 113, 20))
        self.lineEditMac14.setObjectName("lineEditMac14")
        self.lineEditMac15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac15.setGeometry(QtCore.QRect(650, 70, 113, 20))
        self.lineEditMac15.setObjectName("lineEditMac15")
        self.lineEditMac16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMac16.setGeometry(QtCore.QRect(650, 90, 113, 20))
        self.lineEditMac16.setObjectName("lineEditMac16")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(150, 10, 631, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(460, 180, 291, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar9 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar9.setProperty("value", 24)
        self.progressBar9.setObjectName("progressBar9")
        self.verticalLayout_2.addWidget(self.progressBar9)
        self.progressBar10 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar10.setProperty("value", 24)
        self.progressBar10.setObjectName("progressBar10")
        self.verticalLayout_2.addWidget(self.progressBar10)
        self.progressBar11 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar11.setProperty("value", 24)
        self.progressBar11.setObjectName("progressBar11")
        self.verticalLayout_2.addWidget(self.progressBar11)
        self.progressBar12 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar12.setProperty("value", 24)
        self.progressBar12.setObjectName("progressBar12")
        self.verticalLayout_2.addWidget(self.progressBar12)
        self.progressBar13 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar13.setProperty("value", 24)
        self.progressBar13.setObjectName("progressBar13")
        self.verticalLayout_2.addWidget(self.progressBar13)
        self.progressBar14 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar14.setProperty("value", 24)
        self.progressBar14.setObjectName("progressBar14")
        self.verticalLayout_2.addWidget(self.progressBar14)
        self.progressBar15 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar15.setProperty("value", 24)
        self.progressBar15.setObjectName("progressBar15")
        self.verticalLayout_2.addWidget(self.progressBar15)
        self.progressBar16 = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar16.setProperty("value", 24)
        self.progressBar16.setObjectName("progressBar16")
        self.verticalLayout_2.addWidget(self.progressBar16)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 771, 471))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(790, 100, 201, 521))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(400, 180, 56, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 12, 0, 16)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelportcombo9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelportcombo9.setObjectName("labelportcombo9")
        self.verticalLayout_6.addWidget(self.labelportcombo9)
        self.labelportcombo10 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo10.setFont(font)
        self.labelportcombo10.setObjectName("labelportcombo10")
        self.verticalLayout_6.addWidget(self.labelportcombo10)
        self.labelportcombo11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo11.setFont(font)
        self.labelportcombo11.setObjectName("labelportcombo11")
        self.verticalLayout_6.addWidget(self.labelportcombo11)
        self.labelportcombo12 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo12.setFont(font)
        self.labelportcombo12.setObjectName("labelportcombo12")
        self.verticalLayout_6.addWidget(self.labelportcombo12)
        self.labelportcombo13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo13.setFont(font)
        self.labelportcombo13.setObjectName("labelportcombo13")
        self.verticalLayout_6.addWidget(self.labelportcombo13)
        self.labelportcombo14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo14.setFont(font)
        self.labelportcombo14.setObjectName("labelportcombo14")
        self.verticalLayout_6.addWidget(self.labelportcombo14)
        self.labelportcombo15 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo15.setFont(font)
        self.labelportcombo15.setObjectName("labelportcombo15")
        self.verticalLayout_6.addWidget(self.labelportcombo15)
        self.labelportcombo16 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo16.setFont(font)
        self.labelportcombo16.setObjectName("labelportcombo16")
        self.verticalLayout_6.addWidget(self.labelportcombo16)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 180, 291, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar1 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar1.setProperty("value", 24)
        self.progressBar1.setObjectName("progressBar1")
        self.verticalLayout.addWidget(self.progressBar1)
        self.progressBar2 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.verticalLayout.addWidget(self.progressBar2)
        self.progressBar3 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar3.setProperty("value", 24)
        self.progressBar3.setObjectName("progressBar3")
        self.verticalLayout.addWidget(self.progressBar3)
        self.progressBar4 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar4.setProperty("value", 24)
        self.progressBar4.setObjectName("progressBar4")
        self.verticalLayout.addWidget(self.progressBar4)
        self.progressBar5 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar5.setProperty("value", 24)
        self.progressBar5.setObjectName("progressBar5")
        self.verticalLayout.addWidget(self.progressBar5)
        self.progressBar6 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar6.setProperty("value", 24)
        self.progressBar6.setObjectName("progressBar6")
        self.verticalLayout.addWidget(self.progressBar6)
        self.progressBar7 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar7.setProperty("value", 24)
        self.progressBar7.setObjectName("progressBar7")
        self.verticalLayout.addWidget(self.progressBar7)
        self.progressBar8 = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar8.setProperty("value", 24)
        self.progressBar8.setObjectName("progressBar8")
        self.verticalLayout.addWidget(self.progressBar8)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(800, 159, 91, 451))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox1 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox1.setObjectName("comboBox1")
        self.verticalLayout_3.addWidget(self.comboBox1)
        self.comboBox2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox2.setObjectName("comboBox2")
        self.verticalLayout_3.addWidget(self.comboBox2)
        self.comboBox3 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox3.setObjectName("comboBox3")
        self.verticalLayout_3.addWidget(self.comboBox3)
        self.comboBox4 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox4.setObjectName("comboBox4")
        self.verticalLayout_3.addWidget(self.comboBox4)
        self.comboBox5 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox5.setObjectName("comboBox5")
        self.verticalLayout_3.addWidget(self.comboBox5)
        self.comboBox6 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox6.setObjectName("comboBox6")
        self.verticalLayout_3.addWidget(self.comboBox6)
        self.comboBox7 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox7.setObjectName("comboBox7")
        self.verticalLayout_3.addWidget(self.comboBox7)
        self.comboBox8 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox8.setObjectName("comboBox8")
        self.verticalLayout_3.addWidget(self.comboBox8)
        self.comboBox9 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox9.setObjectName("comboBox9")
        self.verticalLayout_3.addWidget(self.comboBox9)
        self.comboBox10 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox10.setObjectName("comboBox10")
        self.verticalLayout_3.addWidget(self.comboBox10)
        self.comboBox11 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox11.setObjectName("comboBox11")
        self.verticalLayout_3.addWidget(self.comboBox11)
        self.comboBox12 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox12.setObjectName("comboBox12")
        self.verticalLayout_3.addWidget(self.comboBox12)
        self.comboBox13 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox13.setObjectName("comboBox13")
        self.verticalLayout_3.addWidget(self.comboBox13)
        self.comboBox14 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox14.setObjectName("comboBox14")
        self.verticalLayout_3.addWidget(self.comboBox14)
        self.comboBox15 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox15.setObjectName("comboBox15")
        self.verticalLayout_3.addWidget(self.comboBox15)
        self.comboBox16 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox16.setObjectName("comboBox16")
        self.verticalLayout_3.addWidget(self.comboBox16)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(890, 158, 91, 451))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelstate1 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate1.setObjectName("labelstate1")
        self.verticalLayout_4.addWidget(self.labelstate1)
        self.labelstate2 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate2.setObjectName("labelstate2")
        self.verticalLayout_4.addWidget(self.labelstate2)
        self.labelstate3 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate3.setObjectName("labelstate3")
        self.verticalLayout_4.addWidget(self.labelstate3)
        self.labelstate4 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate4.setObjectName("labelstate4")
        self.verticalLayout_4.addWidget(self.labelstate4)
        self.labelstate5 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate5.setObjectName("labelstate5")
        self.verticalLayout_4.addWidget(self.labelstate5)
        self.labelstate6 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate6.setObjectName("labelstate6")
        self.verticalLayout_4.addWidget(self.labelstate6)
        self.labelstate7 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate7.setObjectName("labelstate7")
        self.verticalLayout_4.addWidget(self.labelstate7)
        self.labelstate8 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate8.setObjectName("labelstate8")
        self.verticalLayout_4.addWidget(self.labelstate8)
        self.labelstate9 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate9.setObjectName("labelstate9")
        self.verticalLayout_4.addWidget(self.labelstate9)
        self.labelstate10 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate10.setObjectName("labelstate10")
        self.verticalLayout_4.addWidget(self.labelstate10)
        self.labelstate11 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate11.setObjectName("labelstate11")
        self.verticalLayout_4.addWidget(self.labelstate11)
        self.labelstate12 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate12.setObjectName("labelstate12")
        self.verticalLayout_4.addWidget(self.labelstate12)
        self.labelstate13 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate13.setObjectName("labelstate13")
        self.verticalLayout_4.addWidget(self.labelstate13)
        self.labelstate14 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate14.setObjectName("labelstate14")
        self.verticalLayout_4.addWidget(self.labelstate14)
        self.labelstate15 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate15.setObjectName("labelstate15")
        self.verticalLayout_4.addWidget(self.labelstate15)
        self.labelstate16 = QtWidgets.QLabel(self.layoutWidget3)
        self.labelstate16.setObjectName("labelstate16")
        self.verticalLayout_4.addWidget(self.labelstate16)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 180, 56, 421))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 12, 0, 16)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelportcombo1 = QtWidgets.QLabel(self.layoutWidget4)
        self.labelportcombo1.setObjectName("labelportcombo1")
        self.verticalLayout_5.addWidget(self.labelportcombo1)
        self.labelportcombo2 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo2.setFont(font)
        self.labelportcombo2.setObjectName("labelportcombo2")
        self.verticalLayout_5.addWidget(self.labelportcombo2)
        self.labelportcombo3 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo3.setFont(font)
        self.labelportcombo3.setObjectName("labelportcombo3")
        self.verticalLayout_5.addWidget(self.labelportcombo3)
        self.labelportcombo4 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo4.setFont(font)
        self.labelportcombo4.setObjectName("labelportcombo4")
        self.verticalLayout_5.addWidget(self.labelportcombo4)
        self.labelportcombo5 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo5.setFont(font)
        self.labelportcombo5.setObjectName("labelportcombo5")
        self.verticalLayout_5.addWidget(self.labelportcombo5)
        self.labelportcombo6 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo6.setFont(font)
        self.labelportcombo6.setObjectName("labelportcombo6")
        self.verticalLayout_5.addWidget(self.labelportcombo6)
        self.labelportcombo7 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo7.setFont(font)
        self.labelportcombo7.setObjectName("labelportcombo7")
        self.verticalLayout_5.addWidget(self.labelportcombo7)
        self.labelportcombo8 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelportcombo8.setFont(font)
        self.labelportcombo8.setObjectName("labelportcombo8")
        self.verticalLayout_5.addWidget(self.labelportcombo8)
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.StartBurningButton.raise_()
        self.label.raise_()
        self.lineEditCheckSum.raise_()
        self.DetectPortButton.raise_()
        self.OpenPortButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.lineEditMac1.raise_()
        self.lineEditMac2.raise_()
        self.lineEditMac3.raise_()
        self.lineEditMac4.raise_()
        self.lineEditMac5.raise_()
        self.lineEditMac6.raise_()
        self.lineEditMac7.raise_()
        self.lineEditMac8.raise_()
        self.lineEditMac9.raise_()
        self.lineEditMac10.raise_()
        self.lineEditMac11.raise_()
        self.lineEditMac12.raise_()
        self.lineEditMac13.raise_()
        self.lineEditMac14.raise_()
        self.lineEditMac15.raise_()
        self.lineEditMac16.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.SetFileSubMenu = QtWidgets.QAction(MainWindow)
        self.SetFileSubMenu.setObjectName("SetFileSubMenu")
        self.actionpic8 = QtWidgets.QAction(MainWindow)
        self.actionpic8.setObjectName("actionpic8")
        self.actionpic16 = QtWidgets.QAction(MainWindow)
        self.actionpic16.setObjectName("actionpic16")
        self.menu_2.addAction(self.actionpic8)
        self.menu_2.addAction(self.actionpic16)
        self.menu.addAction(self.SetFileSubMenu)
        self.menu.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartBurningButton.setText(_translate("MainWindow", "开始烧录"))
        self.label.setText(_translate("MainWindow", "CheckSum:"))
        self.DetectPortButton.setText(_translate("MainWindow", "探测端口"))
        self.OpenPortButton.setText(_translate("MainWindow", "打开端口"))
        self.label_2.setText(_translate("MainWindow", "1."))
        self.label_3.setText(_translate("MainWindow", "4."))
        self.label_4.setText(_translate("MainWindow", "6."))
        self.label_5.setText(_translate("MainWindow", "7."))
        self.label_6.setText(_translate("MainWindow", "12."))
        self.label_7.setText(_translate("MainWindow", "13."))
        self.label_8.setText(_translate("MainWindow", "3."))
        self.label_9.setText(_translate("MainWindow", "2."))
        self.label_10.setText(_translate("MainWindow", "5."))
        self.label_11.setText(_translate("MainWindow", "8."))
        self.label_12.setText(_translate("MainWindow", "9."))
        self.label_13.setText(_translate("MainWindow", "10."))
        self.label_14.setText(_translate("MainWindow", "11."))
        self.label_15.setText(_translate("MainWindow", "14."))
        self.label_16.setText(_translate("MainWindow", "15."))
        self.label_17.setText(_translate("MainWindow", "16."))
        self.groupBox.setTitle(_translate("MainWindow", "蓝牙地址"))
        self.groupBox_2.setTitle(_translate("MainWindow", "烧录结果"))
        self.groupBox_3.setTitle(_translate("MainWindow", "端口"))
        self.labelportcombo9.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo10.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo11.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo12.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo13.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo14.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo15.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo16.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate1.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate2.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate3.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate4.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate5.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate6.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate7.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate8.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate9.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate10.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate11.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate12.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate13.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate14.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate15.setText(_translate("MainWindow", "TextLabel"))
        self.labelstate16.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo1.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo2.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo3.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo4.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo5.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo6.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo7.setText(_translate("MainWindow", "TextLabel"))
        self.labelportcombo8.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "烧录数量"))
        self.menuAbout.setTitle(_translate("MainWindow", "关于"))
        self.SetFileSubMenu.setText(_translate("MainWindow", "烧录文件"))
        self.actionpic8.setText(_translate("MainWindow", "8"))
        self.actionpic16.setText(_translate("MainWindow", "16"))

